# Generated by Django 4.2.16 on 2026-04-08 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynote',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailynote',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='dailynote',
            unique_together={('owner', 'date')},
        ),
    ]
