# Generated by Django 4.2.16 on 2026-04-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unlocked', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('tasks', 'Tasks'), ('habits', 'Habits'), ('streak', 'Streak'), ('level', 'Level')], max_length=16)),
                ('threshold', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='*', max_length=8)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['threshold', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
