# Generated by Django 4.2.16 on 2026-04-02 12:44

from django.db import migrations, models
import django.utils.timezone


def copy_status_to_completed(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(status="completed").update(completed=True)
    Task.objects.filter(status="pending").update(completed=False)


def reverse_completed_to_status(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(completed=True).update(status="completed")
    Task.objects.filter(completed=False).update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'due_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('main', 'Main Quest'), ('side', 'Side Quest'), ('boss', 'Boss Fight')], default='main', max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='xp_reward',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=160),
        ),
        migrations.RunPython(copy_status_to_completed, reverse_completed_to_status),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
