name: Keep Render Alive
on:
  schedule:
    - cron: '*/10 * * * *'  # runs every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl https://habit-tracker-dashboard-pgo7.onrender.com/